### PR TITLE
fix(metadata): Use mocked library version in Metadata Aspect

### PR DESCRIPTION
**Pull request by akash1810**
## What does this change?

In https://github.com/guardian/cdk/pull/1394 we introduced a Metadata Aspect to enable us to track which specific constructs and patterns are in use, and which version. This manifests itself as `Metadata` in the CloudFormation template.

The version maps to the NPM package version, as such, it changes over time. This means the value stored within snapshot tests would also change. This will become noisy over time.

In https://github.com/guardian/cdk/pull/448 we published a mock and wired every project up to use it. This results in the library version being static in snapshots.

In this change, we update the Metadata Aspect to retrieve the version number in the same way, making it's value static within snapshots also.

This change is an alternative to https://github.com/guardian/cdk/pull/1484. Whilst #1484 would work, it would also require changes to each cdk project's Jest configuration. In this change, we avoid this as they're already configured to use this mocked value.

## How to test

See CI.

## How can we measure success?

Simplifying the upgrade path, as one can just bump the library version.

## Have we considered potential risks?

n/a

## Checklist

- [ ] I have listed any breaking changes, along with a migration path [^1]
- [ ] I have updated the documentation as required for the described changes [^2]

[^1]: Consider whether this is something that will mean changes to projects that have already been migrated, or to the CDK CLI tool. If changes are required, consider adding a checklist here and/or linking to related PRs.
[^2]: If you are adding a new construct or pattern, has new documentation been added? If you are amending defaults or changing behaviour, are the existing docs still valid?

### CODE REVIEW

**Review by nicl — APPROVED** [review]

**Comment by akash1810** [comment]
I think this has broken the package, at least I'm getting this in the tracker repository when upgrading to 47.3.3:

```console
    Cannot find module '@guardian/cdk/lib/constants/tracking-tag' from 'jest.setup.cdk.js'

    > 1 | jest.mock('@guardian/cdk/lib/constants/tracking-tag');
        |                          ^
      2 |
```
